### ISSUE TITLE
Make easta() accept a code-point as input

### ISSUE THREAD

**Issue by sedwards2009** [teppeis/easta#33]
For me at least it would be handy if `easta()` could accept a code-point (number) as input along side the current string.

**Comment by teppeis** [comment]
Please define your wrapper function like

```js
function eastaFromCodePoint(cp) {
  return easta(String.fromCodePoint(cp));
}

// `W`
eastaFromCodePoint(0x1F6F8);
```

or just use Unicode code point escapes like `easta("\u{1F6F8}")`
